COSMOLOGY:
  Battaglia2012:
    flat: True 
    H0: 70
    Omega_m0: 0.25
    Omega_b0: 0.043
    sigma8: 0.8
    ns: 0.96
    cosmo_h: 0.7
    t_cmb: 2.725 #K

SURVEYS:
  ACTDR5:
    150: #Observation frequency [GHz]
      beam_size: 1.4 #From published survey properties
      noise_level: 8 #[uK/arcmin]
  
IMAGES:
  image_size_pixels: 41
  pixel_size_arcmin: 0.5
    

    
