name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: base-test
    - name: Install dependencies
      run: |
        # conda env update --file=../environment.yml --name=base-test
        # python -m pip install colossus pixell camb
        cd ..
        ls
        pwd
        python -m pip install .
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
